@echo off
set SUPABASE_URL=***REMOVED-ROTATE-CREDENTIAL***
set SUPABASE_ANON_KEY=***REMOVED-ROTATE-CREDENTIAL***
set LINE_CHANNEL_SECRET=***REMOVED-ROTATE-CREDENTIAL***
set LINE_CHANNEL_ACCESS_TOKEN=***REMOVED-ROTATE-CREDENTIAL***
set LIFF_ID=***REMOVED-ROTATE-CREDENTIAL***
set STORE_ID=***REMOVED-ROTATE-CREDENTIAL***

node server.js