name: Deploy to GCP (Dev) - Optimized

on:
  push:
    branches: [dev]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.github/**'
      - '!.github/workflows/deploy-dev.yml'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID_DEV }}
  REGION: asia-northeast1
  SERVICE: line-booking-api-dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # タイムアウト設定（コスト削減）
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # GCP認証
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY_DEV }}
    
    # gcloud CLIセットアップ
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    # 直接Cloud Runへデプロイ（Buildを使わない = 無料）
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE \
          --source . \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --min-instances 0 \
          --max-instances 10 \
          --cpu 1 \
          --memory 512Mi \
          --timeout 60 \
          --project $PROJECT_ID \
          --update-secrets=LINE_CHANNEL_ACCESS_TOKEN=line-channel-access-token:latest,LINE_CHANNEL_SECRET=line-channel-secret:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest \
          --set-env-vars=NODE_ENV=development,STORE_ID=default-store,LIFF_ID=2006487876-xd1A5qJB
    
    # スモークテスト
    - name: Smoke Test
      run: |
        SERVICE_URL=$(gcloud run services describe $SERVICE --region $REGION --format 'value(status.url)' --project $PROJECT_ID)
        echo "Testing $SERVICE_URL/api/ping"
        curl -f "$SERVICE_URL/api/ping" || exit 1
        echo "✅ Health check passed"